### ISSUE TITLE
POST Request won't give response

### ISSUE THREAD

**Issue by takahser** [scotch-io/node-api#5]
It seems as I can't connect to the DB. If I try to make a POST on api/bears with the key[name=Klaus] using POSTMAN nothing would happen (I followed you instruction on http://scotch.io/tutorials/javascript/build-a-restful-api-using-node-and-express-4 ).

**Comment by scottstensland** [comment]
Yes I am getting same HANGING issue due to obsolete database as per

var mongoose   = require('mongoose');
mongoose.connect('mongodb://node:node@novus.modulusmongo.net:27017/Iganiq8o');

**Comment by oscarmorrison** [comment]
bump

**Comment by sevilayha** [comment]
Is it not working when using a local mongodb database? 

That demo database `mongodb://node:node@novus.modulusmongo.net:27017/Iganiq8o` was shut down because too many people were just using that instead of creating their own.

**Comment by garryhicks** [comment]
I am having the same issue. Instead of using a local mongodb, I am supplying the credentials to my own hosted mongolab database and everything.

**Comment by oscarmorrison** [comment]
I got it working with local DB. Won't work with my own mongo lab for some reason

**Comment by garryhicks** [comment]
Did you end up having to use an alternative db?

**Comment by garryhicks** [comment]
I updated my version, I had been using an old version. It works great now.

**Comment by ElectronHarvester** [comment]
I have a pull request pending that solves this issue.

**Comment by sevilayha** [comment]
Thanks for the PR @ElectronHarvester!

**Comment by ElectronHarvester** [comment]
No problem! Thanks for sharing your simple node-api app!

**Comment by ElectronHarvester** [comment]
@sevilayha Thanks for sharing a good simple node api app!

**Comment by pavanyogi** [comment]
After creating local database , it works fine ... :) 
database creation in mongodb 
-------------------
Server\3.4\bin>mongo.exe
MongoDB shell version v3.4.2
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.4.2
Server has startup warnings:
2017-03-03T11:35:46.632+0530 I CONTROL  [initandlisten]
2017-03-03T11:35:46.632+0530 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-03-03T11:35:46.633+0530 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-03-03T11:35:46.633+0530 I CONTROL  [initandlisten]
> show dbs
admin  0.000GB
local  0.000GB
> use mydb
switched to db mydb
> db
mydb
> show dbs
admin  0.000GB
local  0.000GB
> db.movie.insert({"name":"abc"})
WriteResult({ "nInserted" : 1 })
> show dbs
admin  0.000GB
local  0.000GB
mydb   0.000GB
>

----------------------
server.js  part
mongoose.connect('mongodb://127.0.0.1/mydb'); // connect to our database
